In [1]:
import numpy as np

In [2]:
def relu(x):
    return np.maximum(0, x)

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [4]:
def tanh(x):
    return np.tanh(x)

In [5]:
def softmax(x):
    exp_x = np.exp(x - np.max(x))  # Stability trick
    return exp_x / np.sum(exp_x)

In [6]:

x = np.array([-2, -1, 0, 1, 2])

print("Input:")
print(x)

Input:
[-2 -1  0  1  2]


***1. ReLu***

In [7]:
print("\nReLU Output:")
print(relu(x))


ReLU Output:
[0 0 0 1 2]


***2. Sigmoid***

In [8]:
print("\nSigmoid Output:")
print(sigmoid(x))



Sigmoid Output:
[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


***3. Tanh***

In [9]:
print("\nTanh Output:")
print(tanh(x))


Tanh Output:
[-0.96402758 -0.76159416  0.          0.76159416  0.96402758]


***4. SoftMax***

In [10]:
print("\nSoftmax Output:")
print(softmax(x))

print("\nSum of Softmax Probabilities:")
print(np.sum(softmax(x)))


Softmax Output:
[0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]

Sum of Softmax Probabilities:
1.0
