In [1]:
import torch

In [3]:

x = torch.tensor([1,2,3])

print(x)

tensor([1, 2, 3])


***Float Tensor***

In [5]:
x = torch.tensor([1.0,2.0,3.0])
x

tensor([1., 2., 3.])

In [6]:
x = torch.zeros(3,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
x = torch.rand(2,3)
x

tensor([[0.8631, 0.9729, 0.9247],
        [0.1062, 0.3013, 0.4713]])

In [9]:
x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

print(x.shape)

torch.Size([2, 3])


***1. Addition***

In [11]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a+b)

tensor([5, 7, 9])


***Multiplication***

In [12]:
a*b

tensor([ 4, 10, 18])

***Matrix Multiplication***

In [13]:
A = torch.tensor([[1,2],
                  [3,4]])

B = torch.tensor([[5,6],
                  [7,8]])

print(torch.matmul(A,B))

tensor([[19, 22],
        [43, 50]])
