In [17]:
import torch
import torch.nn as nn

In [18]:
x = torch.tensor([[[1.0],
                   [2.0],
                   [3.0]]])


In [19]:

lstm = nn.LSTM(
    input_size=1,
    hidden_size=4,
    num_layers=1,
    batch_first=True
)

In [20]:
output, (hidden_state, cell_state) = lstm(x)

In [21]:
print("Output:")
print(output)

Output:
tensor([[[-0.0080, -0.0872,  0.0104,  0.0635],
         [ 0.0339, -0.2258,  0.1727,  0.1418],
         [ 0.0548, -0.4042,  0.3694,  0.2156]]], grad_fn=<TransposeBackward0>)


In [22]:
print("\nFinal Hidden State (hn):")
print(hn)


Final Hidden State (hn):
tensor([[[ 0.0586, -0.3710,  0.0398,  0.4355]]], grad_fn=<StackBackward0>)


In [23]:

print("\nFinal Cell State (cn):")
print(cn)


Final Cell State (cn):
tensor([[[ 0.0971, -0.8076,  0.1404,  0.6631]]], grad_fn=<StackBackward0>)


In [24]:
print("\nCell State Shape:")
print(cell_state.shape)


Cell State Shape:
torch.Size([1, 1, 4])
